export const resourceConfigs = {
  products: {
    title: 'Products',
    subtitle: 'Manage SKUs, stock, pricing, SEO and product media.',
    createPath: '/admin/products/create',
    editPath: (id) => `/admin/products/edit/${id}`,
    columns: [
      { key: 'name', label: 'Product' },
      { key: 'sku', label: 'SKU' },
      { key: 'category.name', label: 'Category' },
      { key: 'brand.name', label: 'Brand' },
      { key: 'price', label: 'Price', format: 'currency' },
      { key: 'stockQuantity', label: 'Stock' },
      { key: 'status', label: 'Status' },
    ],
  },
  categories: {
    title: 'Categories',
    subtitle: 'Build nested merchandising categories.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
      { key: 'status', label: 'Active', format: 'boolean' },
    ],
    fields: [
      { name: 'name', label: 'Category name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'description', label: 'Description', multiline: true },
      { name: 'status', label: 'Active', type: 'boolean', defaultValue: true },
    ],
  },
  brands: {
    title: 'Brands',
    subtitle: 'Maintain brand names, logos and active status.',
    columns: [
      { key: 'name', label: 'Brand' },
      { key: 'slug', label: 'Slug' },
      { key: 'status', label: 'Active', format: 'boolean' },
    ],
    fields: [
      { name: 'name', label: 'Brand name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'description', label: 'Description', multiline: true },
      { name: 'status', label: 'Active', type: 'boolean', defaultValue: true },
    ],
  },
  orders: {
    title: 'Orders',
    subtitle: 'Review orders, update fulfillment status and prepare invoices.',
    columns: [
      { key: 'orderNumber', label: 'Order' },
      { key: 'customer.email', label: 'Customer' },
      { key: 'status', label: 'Status' },
      { key: 'paymentStatus', label: 'Payment' },
      { key: 'grandTotal', label: 'Total', format: 'currency' },
      { key: 'createdAt', label: 'Created', format: 'date' },
    ],
    fields: [
      { name: 'status', label: 'Order status', type: 'select', options: ['PENDING', 'CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED'] },
      { name: 'paymentStatus', label: 'Payment status', type: 'select', options: ['PENDING', 'PAID', 'FAILED', 'REFUNDED'] },
    ],
    disableCreate: true,
  },
  customers: {
    title: 'Customers',
    subtitle: 'Manage profiles, status, notes and purchase context.',
    columns: [
      { key: 'firstName', label: 'First name' },
      { key: 'lastName', label: 'Last name' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'firstName', label: 'First name', required: true },
      { name: 'lastName', label: 'Last name' },
      { name: 'email', label: 'Email', required: true },
      { name: 'phone', label: 'Phone' },
      { name: 'status', label: 'Status', type: 'select', options: ['ACTIVE', 'INACTIVE', 'SUSPENDED'] },
    ],
  },
  inventory: {
    title: 'Inventory',
    subtitle: 'Track stock quantity, low stock thresholds and movement health.',
    columns: [
      { key: 'product.name', label: 'Product' },
      { key: 'product.sku', label: 'SKU' },
      { key: 'stockQuantity', label: 'Stock' },
      { key: 'reservedQuantity', label: 'Reserved' },
      { key: 'lowStockThreshold', label: 'Low stock at' },
      { key: 'stockStatus', label: 'Status' },
    ],
    disableCreate: true,
  },
  coupons: {
    title: 'Coupons',
    subtitle: 'Create percentage, fixed and free-shipping promotions.',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'discountType', label: 'Type' },
      { key: 'discountValue', label: 'Value' },
      { key: 'usageLimit', label: 'Limit' },
      { key: 'usedCount', label: 'Used' },
      { key: 'isActive', label: 'Active', format: 'boolean' },
    ],
    fields: [
      { name: 'code', label: 'Coupon code', required: true },
      { name: 'discountType', label: 'Discount type', type: 'select', options: ['PERCENTAGE', 'FIXED', 'FREE_SHIPPING'] },
      { name: 'discountValue', label: 'Discount value', type: 'number' },
      { name: 'usageLimit', label: 'Usage limit', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true },
    ],
  },
  reviews: {
    title: 'Reviews',
    subtitle: 'Approve, reject and analyze customer product feedback.',
    columns: [
      { key: 'product.name', label: 'Product' },
      { key: 'customer.email', label: 'Customer' },
      { key: 'rating', label: 'Rating' },
      { key: 'title', label: 'Title' },
      { key: 'status', label: 'Status' },
    ],
    disableCreate: true,
  },
  banners: {
    title: 'Banners',
    subtitle: 'Manage homepage sliders, promotional, popup and mobile banners.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type' },
      { key: 'imageUrl', label: 'Image' },
      { key: 'isEnabled', label: 'Enabled', format: 'boolean' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'type', label: 'Banner type', type: 'select', options: ['HOMEPAGE_SLIDER', 'PROMOTIONAL', 'POPUP', 'MOBILE'] },
      { name: 'imageUrl', label: 'Image URL', required: true },
      { name: 'isEnabled', label: 'Enabled', type: 'boolean', defaultValue: true },
    ],
  },
  'cms-pages': {
    title: 'CMS Pages',
    subtitle: 'Maintain Home, About, Contact, Privacy, Terms and FAQ content.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'status', label: 'Status' },
      { key: 'updatedAt', label: 'Updated', format: 'date' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED', 'ARCHIVED'] },
      { name: 'content', label: 'Content', multiline: true, required: true },
    ],
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Track new order, low stock and customer registration alerts.',
    columns: [
      { key: 'type', label: 'Type' },
      { key: 'title', label: 'Title' },
      { key: 'message', label: 'Message' },
      { key: 'isRead', label: 'Read', format: 'boolean' },
      { key: 'createdAt', label: 'Created', format: 'date' },
    ],
    disableCreate: true,
  },
  users: {
    title: 'Users',
    subtitle: 'Manage super admins, admins, managers, inventory staff and support users.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'roles', label: 'Roles', format: 'array' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'email', label: 'Email', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['ACTIVE', 'INACTIVE', 'SUSPENDED'] },
    ],
  },
  roles: {
    title: 'Roles',
    subtitle: 'Define access groups and attach permissions.',
    columns: [
      { key: 'name', label: 'Role' },
      { key: 'slug', label: 'Slug' },
      { key: 'permissionSlugs', label: 'Permissions', format: 'array' },
      { key: 'isSystem', label: 'System', format: 'boolean' },
    ],
    fields: [
      { name: 'name', label: 'Role name', required: true },
      { name: 'slug', label: 'Slug' },
      { name: 'description', label: 'Description', multiline: true },
    ],
  },
  permissions: {
    title: 'Permissions',
    subtitle: 'Create, edit and delete module-level access rules.',
    columns: [
      { key: 'name', label: 'Permission' },
      { key: 'slug', label: 'Slug' },
      { key: 'module', label: 'Module' },
      { key: 'createdAt', label: 'Created', format: 'date' },
    ],
    fields: [
      { name: 'name', label: 'Permission name', required: true },
      { name: 'slug', label: 'Slug', required: true },
      { name: 'module', label: 'Module', required: true },
    ],
  },
  settings: {
    title: 'Settings',
    subtitle: 'Website, email, payment, shipping and tax configuration.',
    columns: [
      { key: 'group', label: 'Group' },
      { key: 'key', label: 'Key' },
      { key: 'value', label: 'Value', format: 'json' },
      { key: 'isPublic', label: 'Public', format: 'boolean' },
    ],
    fields: [
      { name: 'group', label: 'Group', required: true },
      { name: 'key', label: 'Key', required: true },
      { name: 'value', label: 'Value', required: true },
      { name: 'isPublic', label: 'Public', type: 'boolean' },
    ],
  },
  'activity-logs': {
    title: 'Activity Logs',
    subtitle: 'Track login activity, product changes, order updates and user actions.',
    columns: [
      { key: 'module', label: 'Module' },
      { key: 'action', label: 'Action' },
      { key: 'user.email', label: 'User' },
      { key: 'entity', label: 'Entity' },
      { key: 'createdAt', label: 'Created', format: 'date' },
    ],
    disableCreate: true,
    disableEdit: true,
    disableDelete: true,
  },
};