FROM node:20-alpine

WORKDIR /app/server

COPY server/package*.json ./
RUN npm ci

COPY server/prisma ./prisma
RUN npx prisma generate

COPY server ./

EXPOSE 5000

CMD ["sh", "-c", "npx prisma migrate deploy && node index.js"]
